permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: KinTeam
  email: 1015709746@qq.com
  link: http://youwozai.github.io
  github: http://github.com/youwozai


# 站点信息
title: KinTeam的博客
description: KinTeam blog
url: http://youwozai.github.io
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/xiaomage.jpg
favicon: /public/img/xiaomage.jpg

# google analytics 设置
ga:
  id: UA-54262064-1 
  url: painterlin.com

# disqus 设置
disqus:
  shortname: painterlin

# 主题设置，自动激活某个标签
active: 读书

# 首页除了最新文章外显示分类
cates: 
  - Optimization
  - LaTeX

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档